type SystemNamesKeys = keyof typeof SystemNames;
export type ValidSystemNames = typeof SystemNames[SystemNamesKeys];

export const SystemNames = {
  Authentication: "Authentication",
  BungieTokens: "BungieTokens",
  Clans: "Clans",
  CodeRedemptionReact: "CodeRedemptionReact",
  CoreAreaSeasons: "CoreAreaSeasons",
  CoreDestinyBuy: "CoreDestinyBuy",
  CrossSave: "CrossSave",
  CrossSaveStadiaException: "CrossSaveStadiaSeasonsException",
  Destiny2: "Destiny2",
  FacebookPixel: "FacebookPixel",
  Forums: "Forums",
  GamescomVideo: "GamescomVideo",
  GoogleAnalytics: "GoogleAnalytics",
  Groups: "Groups",
  Localizer: "Localizer",
  LocalizerDebug: "LocalizerDebug",
  LunaVideo: "LunaVideo",
  Messages: "Messages",
  Notifications: "Notifications",
  PartnerOfferClaims: "PartnerOfferClaims",
  PCMigration: "PCMigration",
  PCMigrationYoutubeIdFallback: "PCMigrationYoutubeIdFallback",
  PlayTestsSetting: "PlayTestsSetting",
  SeasonUndyingVideo: "SeasonUndyingVideo",
  PSNAuth: "PSNAuth",
  XuidAuth: "XuidAuth",
  Twitch: "Twitch",
  Blizzard: "Blizzard",
  StadiaIdAuth: "StadiaIdAuth",
} as const;
