type SystemNamesKeys = keyof typeof SystemNames;
export type ValidSystemNames = typeof SystemNames[SystemNamesKeys];

export const SystemNames = {
  Applications: "Applications",
  Authentication: "Authentication",
  BuyFlow: "BuyFlow",
  BungieTokens: "BungieTokens",
  Clans: "Clans",
  CodeRedemptionReact: "CodeRedemptionReact",
  CoreAreaSeasons: "CoreAreaSeasons",
  CoreDestinyBuy: "CoreDestinyBuy",
  CrossSave: "CrossSave",
  CrossSaveStadiaException: "CrossSaveStadiaSeasonsException",
  Destiny2: "Destiny2",
  FacebookPixel: "FacebookPixel",
  Forums: "Forums",
  GamescomVideo: "GamescomVideo",
  GoogleAnalytics: "GoogleAnalytics",
  Groups: "Groups",
  Localizer: "Localizer",
  LocalizerDebug: "LocalizerDebug",
  LunaVideo: "LunaVideo",
  Messages: "Messages",
  Notifications: "Notifications",
  PartnerOfferClaims: "PartnerOfferClaims",
  PCMigration: "PCMigration",
  PCMigrationYoutubeIdFallback: "PCMigrationYoutubeIdFallback",
  PlayTestsSetting: "PlayTestsSetting",
  SeasonUndyingVideo: "SeasonUndyingVideo",
  PSNAuth: "PSNAuth",
  XuidAuth: "XuidAuth",
  Twitch: "Twitch",
  Blizzard: "Blizzard",
  SteamIdAuth: "SteamIdAuth",
  StadiaIdAuth: "StadiaIdAuth",
  PrePCMigration: "PrePCMigration",
  PCMigrationLoginInterrupt: "PCMigrationLoginInterrupt",
  Season11Page: "Season11Page",
  Season10GoLive: "Season10GoLive",
  StadiaLimited: "StadiaLimited",
  PCMigrationEntitlements: "PCMigrationEntitlements",
  PCMigrationEmailValidation: "PCMigrationEmailValidation",
  RealTimeCounts: "RealTimeCounts",
  PCMigrationGlobalAlertsBar: "PCMigrationGlobalAlertsBar",
  SessionTracking: "SessionTracking",
  DestinyMarketingPages: "DestinyMarketingPages",
  CookieConsent: "CookieConsent",
  PrivacyAuthCheck: "PrivacyAuthCheck",
  RegistrationBenefitsContentVersion2: "RegistrationBenefitsContentVersion2",
  RegistrationBenefitsEnabled: "RegistrationBenefitsEnabled",
  RegistrationUI: "RegistrationUI",
  RegistrationNavVersion2: "RegistrationNavVersion2",
  BeyondLightRevealYoutube: "BeyondLightRevealYoutube",
  BeyondLightGamePlayYoutube: "BeyondLightGamePlayYoutube",
} as const;
